<?php 

function cli_update_channel($channel_id)
{
  if ($channel_id)
  {
    $s = new Youtube();
    echo $s->updateChannel($channel_id) . "\n";
  }
  else
  {
    echo "Missing id parameter. Make sure you typed \"--id\" insted of \"-id\", and try again. ";
  }
}

function cli_update_all_channels()
{
  $s = new Youtube();
  echo $s->updateAllChannels() . "\n";
}

function cli_update_channels_list()
{
  $s = new Youtube();
  echo $s->updateChannelsList();
}

function cli_build_channel($channel_id, $page = false)
{
  if (!$channel_id)
  {
    echo "Missing --id parameter. Make sure you typed \"--id\" insted of \"-id\", and try again. ";
    return;
  }
  $s = new Youtube();
  $result = $s->updateChannel($channel_id, $page);
  echo $result . "\n";

  $result = json_decode($result);
  if ($result->{'next-page'})
  {
    cli_build_channel($channel_id, $result->{'next-page'});
    return;
  }
  else
  {
    echo "\nIt looks like the channel has successfuly build.";
    cli_update_all_channels();
  }
}

function cli_get_videos($from, $to, $all = false)
{
  if ($all)
  {
    $s = new Youtube();
    echo $s->getAllVideos();
  }
  else if ($from && $to)
  {
    $s = new Youtube();
    echo $s->getVideos($from, $to);
  }
  else
  {
    echo "Missing parameters. Try --all to get all videos, or --from <number_1> --to <number_2> to select videos between selected IDs. ";
  }
}

function cli_get_video($id)
{
  if (!$id)
  {
    echo 'Missing --id <number> parameter.';
  }
  else
  {
    $s = new Youtube();
    echo $s->getVideo($id);
  }
}

function cli_get_channel($id)
{
  if (!$id)
  {
    echo 'Missing --id <channel_id> parameter.';
  }
  else 
  {
    $s = new Youtube();
    echo $s->getAllVideosFromChannel($id);
  }
}

function cli_get_all_channels()
{
  $s = new Youtube();
  echo $s->getAllChannels();
}

function cli_clear_database()
{
  $s = new Youtube();
  echo $s->__clearDatabaseFromTrashyRecords();
}

function cli_clear_404()
{
  $s = new Youtube();
  echo $s->__clearDatabaseFrom404Records();
}

function cli_test_url($url)
{
  if (checkUrl($url))
  {
    echo 'OK';
  }
  else
  {
    echo "FAIL";
  }
}

function cli_build_channel_sql($channel_id, $check_urls = false)
{
  if (!$channel_id)
  {
    echo "Missing --channel_id parameter. Provide the YouTube channel ID (e.g. UCxxxxxxxx).\n";
    return;
  }

  $api_key = isset($_SERVER['YOUTUBE_API_KEY']) ? $_SERVER['YOUTUBE_API_KEY'] : false;
  if (!$api_key)
  {
    echo "Missing YOUTUBE_API_KEY in .env file.\n";
    return;
  }

  $uploads_playlist_id = preg_replace('/^UC/', 'UU', $channel_id);
  echo "Channel: $channel_id\n";
  echo "Uploads playlist: $uploads_playlist_id\n\n";

  $all_items = [];
  $channel_title = null;
  $next_page = false;
  $page_count = 0;

  do
  {
    $page_count++;
    echo "Fetching page $page_count...";

    $data = _fetch_playlist_items($uploads_playlist_id, $api_key, $next_page);

    if (!is_object($data))
    {
      echo "\nError fetching data from YouTube API.\n";
      return;
    }

    if (isset($data->error))
    {
      echo "\nYouTube API Error: " . $data->error->message . "\n";
      return;
    }

    if ($data && isset($data->items))
    {
      foreach ($data->items as $item)
      {
        if (isset($item->snippet->resourceId) && isset($item->snippet->resourceId->videoId))
        {
          $all_items[] = $item;
          if (!$channel_title && isset($item->snippet->channelTitle))
          {
            $channel_title = $item->snippet->channelTitle;
          }
        }
      }
    }

    $video_count = count($all_items);
    echo " $video_count videos so far.\n";

    $next_page = isset($data->nextPageToken) ? $data->nextPageToken : false;

  } while ($next_page);

  if (empty($all_items))
  {
    echo "No videos found for channel: $channel_id\n";
    return;
  }

  echo "\nTotal videos: " . count($all_items) . "\n";
  echo "Channel: $channel_title\n";
  echo "Generating SQL...\n";

  if ($check_urls)
  {
    echo "Checking thumbnail URLs (this may take a while)...\n";
  }

  $e = function($val) { return preg_replace("/'/i", "|", $val); };

  $sql = "-- Generated by cli_build_channel_sql\n";
  $sql .= "-- Channel: $channel_title ($channel_id)\n";
  $sql .= "-- Date: " . date('Y-m-d H:i:s') . "\n";
  $sql .= "-- Videos: " . count($all_items) . "\n\n";

  $sql .= "INSERT IGNORE INTO `channels` (`channel_id`, `channel_title`) VALUES ('" . $e($channel_id) . "', '" . $e($channel_title) . "');\n\n";

  $batch_size = 50;
  $batches = array_chunk($all_items, $batch_size);

  foreach ($batches as $batch_index => $batch)
  {
    $sql .= "INSERT IGNORE INTO `music` (\n";
    $sql .= "  `id`, `channel_id`, `video_id`, `title`, `url`,\n";
    $sql .= "  `published_at`, `default_thumbnail`, `medium_thumbnail`,\n";
    $sql .= "  `high_thumbnail`, `channel_title`, `hide`\n";
    $sql .= ") VALUES\n";

    $values = [];
    foreach ($batch as $item)
    {
      $video_id = $item->snippet->resourceId->videoId;

      $set_hide = "NULL";
      if ($check_urls)
      {
        if (!checkUrl($item->snippet->thumbnails->medium->url))
        {
          $set_hide = "1";
        }
      }

      $values[] = sprintf(
        "(NULL, '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', %s)",
        $e($item->snippet->channelId),
        $e($video_id),
        $e($item->snippet->title),
        $e($video_id),
        $e($item->snippet->publishedAt),
        $e($item->snippet->thumbnails->default->url),
        $e($item->snippet->thumbnails->medium->url),
        $e($item->snippet->thumbnails->high->url),
        $e($item->snippet->channelTitle),
        $set_hide
      );
    }

    $sql .= implode(",\n", $values) . ";\n\n";
  }

  $safe_id = preg_replace('/[^a-zA-Z0-9_-]/', '_', $channel_id);
  $filename = __DIR__ . '/' . $safe_id . '_' . date('Y-m-d_His') . '.sql';
  file_put_contents($filename, $sql);

  echo "\nSQL file saved to: $filename\n";
  echo "Import this file via phpMyAdmin to add the channel and its videos.\n";
}

function _fetch_playlist_items($playlist_id, $api_key, $next_page = false)
{
  $options = array(
    'part' => 'snippet',
    'playlistId' => $playlist_id,
    'maxResults' => 50,
    'key' => $api_key
  );

  if ($next_page)
  {
    $options['pageToken'] = $next_page;
  }

  $url = "https://www.googleapis.com/youtube/v3/playlistItems?" . http_build_query($options, 'a', '&');
  $curl = curl_init($url);

  curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_ANY);
  curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($curl, CURLOPT_REFERER, "http://katalog.metalmusic.pl");

  $json_response = curl_exec($curl);
  curl_close($curl);

  return json_decode($json_response);
}